### ISSUE TITLE
Why not support Brisk menu instead of forking Mint menu?

### ISSUE THREAD

**Issue by baimafeima** [ukui/ukui-menu#1]
https://github.com/solus-project/brisk-menu/releases

**Comment by handsome-feng** [comment]
My fault, we just noticed this project, it's very good! I guess we can learn from each other, thank you!

**Comment by cinnamoner** [comment]
@handsome-feng You bet. Brisk is a fine menu. On the other hand, I like the UKUI menu very much (especially the layout). I've spoken to a bunch of people coming over from Windows and they seem to like the UKUI menu a great deal. This is not about Windows though. It just so happens the Windows menus (Vista and 7) are well designed. Perhaps you're aware of StarkMenu. It's fully operational on Cinnamon. It's  worth checking. I have come to favour Mate over Cinnamon for a variety of reasons. To wrapp this up, yes, indeed you should collaborate and come up with a menu that is as close as possible to the Windows menu. Great design is great design and one should put aside his/her feeling in conjunction with Windows (whether positive or not so positive). Please make a menu that is virtually undistinguisahable from the Windows menu. It has been achieved in Cinnamon (Stark) so why shouldn't it be achievable in Mate? At least consider it as an alternative endeavour. Thanks for reading through. I've got high hopes.
***
At least make the UKUI menu fully compatible with Ubuntu Mate 16.04.
***
Also, there seems to be a bug in conjunction with search in the UKUI menu. Nothing serious but annoying. The bug is captured in a video that I'm linking shortly.

**Comment by cinnamoner** [comment]
@handsome-feng Here's the vide capturing the bug https://youtu.be/aRqXfkyYgsE

**Comment by cinnamoner** [comment]
@handsome-feng I think Chinese people are highly innovative. And for the most part everything is made in China. And of course, Chinese civilization predates western civilization. Bottom line: I like the UKUI menu and the UKUI as a whole. I like the reasoning behind it. So, when do you think UKUI final version will land?

**Comment by cinnamoner** [comment]
@handsome-feng Okay. What Dave (the guy in the video failed to understand is: this is not Mate. It's a fork of Mate. Actually, it's much better than the original Mate. This is awesome work and I like it. And the UKUI menu is better than Brisk. Might have that bug or might not, I don't yet known. But overall, it's a better menu than Brisk. That's my opinion.
